
import { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const initialProducts: Product[] = [
  {
    id: '1',
    name: 'The Minimalist Tote',
    description: 'A stylish modern tote with a minimalist design, perfect for any contemporary living space. Upholstered in a durable fabric with solid wood legs.',
    price: 249.99,
    originalPrice: 299.99,
    hasDiscount: true,
    discountPercentage: 16.67,
    imageUrl: PlaceHolderImages.find(p => p.id === '1')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '1')?.imageHint || 'modern chair',
    stock: 15,
    category: 'Handbags',
    audience: 'For Her',
    featured: true,
    wishlistCount: 0,
  },
  {
    id: '2',
    name: 'The Voyager Wallet',
    description: 'A sleek, wooden desk lamp that provides warm, ambient light for your workspace. Features an adjustable arm and a minimalist aesthetic.',
    price: 79.99,
    imageUrl: PlaceHolderImages.find(p => p.id === '2')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '2')?.imageHint || 'desk lamp',
    stock: 30,
    category: 'Accessory',
    audience: 'For Him',
    featured: true,
    wishlistCount: 0,
  },
  {
    id: '3',
    name: 'The City Slicker Bag',
    description: 'A comfortable and elegant sofa for your living room, upholstered in high-quality linen. Its deep seats and plush cushions offer ultimate relaxation.',
    price: 899.99,
    imageUrl: PlaceHolderImages.find(p => p.id === '3')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '3')?.imageHint || 'elegant sofa',
    stock: 10,
    category: 'Backpack',
    audience: 'For Him',
    featured: true,
    wishlistCount: 0,
  },
  {
    id: '4',
    name: 'The Bohemian Clutch',
    description: 'A set of four ceramic mugs, each with a unique reactive glaze. Dishwasher and microwave safe, perfect for your morning coffee or tea.',
    price: 39.99,
    originalPrice: 49.99,
    hasDiscount: true,
    discountPercentage: 20,
    imageUrl: PlaceHolderImages.find(p => p.id === '4')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '4')?.imageHint || 'ceramic mugs',
    stock: 50,
    category: 'Handbags',
    audience: 'For Her',
    featured: true,
    wishlistCount: 0,
  },
  {
    id: '5',
    name: 'The Weekender Duffel',
    description: 'A silent, non-ticking minimalist wall clock with a clean face and wooden hands. Adds a touch of modern simplicity to any room.',
    price: 165.00,
    imageUrl: PlaceHolderImages.find(p => p.id === '5')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '5')?.imageHint || 'wall clock',
    stock: 25,
    category: 'Backpack',
    audience: 'For Him',
    featured: false,
    wishlistCount: 0,
  },
  {
    id: '6',
    name: 'The Everyday Crossbody',
    description: 'A plush, soft-touch area rug featuring a modern geometric pattern. Adds texture and style to your bedroom or living area.',
    price: 129.50,
    imageUrl: PlaceHolderImages.find(p => p.id === '6')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '6')?.imageHint || 'area rug',
    stock: 20,
    category: 'Handbags',
    audience: 'For Her',
    featured: false,
    wishlistCount: 0,
  },
  {
    id: '7',
    name: 'The Classic Bifold',
    description: 'A set of three ceramic hanging planters, ideal for creating a vibrant indoor garden. Comes with adjustable ropes for easy installation.',
    price: 55.99,
    imageUrl: PlaceHolderImages.find(p => p.id === '7')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '7')?.imageHint || 'hanging planters',
    stock: 40,
    category: 'Accessory',
    audience: 'For Him',
    featured: false,
    wishlistCount: 0,
  },
  {
    id: '8',
    name: 'The Evening Wristlet',
    description: 'An artisanal decorative bowl handcrafted from solid acacia wood. Perfect as a centerpiece or for holding keys and other small items.',
    price: 85.00,
    imageUrl: PlaceHolderImages.find(p => p.id === '8')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === '8')?.imageHint || 'wooden bowl',
    stock: 35,
    category: 'Handbags',
    audience: 'For Her',
    featured: false,
    wishlistCount: 0,
  },
];

export const getInitialProducts = () => initialProducts;
